### ISSUE TITLE
prefix search issue

### ISSUE THREAD

**Issue by jojo05** [plar/go-adaptive-radix-tree#1]
I insert "elector", "electibles" and then "elect", "electible"
Below are the prefix queries after each insert. The last "electible" is missing. Is this a bug ?

Thanks
[t-art.txt](https://github.com/plar/go-adaptive-radix-tree/files/868217/t-art.txt)

 
 
 -> <nil>
electibles -> 1
elector -> 0
---
 -> <nil>
elect -> 0
electibles -> 1
elector -> 0

**Comment by dimonwtf** [comment]
Hi, thanks for the bug report. It is fixed.

**Comment by jojo05** [comment]
It works now. Thanks
