### ISSUE TITLE
Prev method or descending order

### ISSUE THREAD

**Issue by recoilme** [plar/go-adaptive-radix-tree#2]
Hello
Is it possible? Give me a direction, please...

**Comment by plar** [comment]
Check it here
https://github.com/plar/go-adaptive-radix-tree/blob/master/tree_traversal.go#L71-L73
. The callback should be called after the `switch` block.
In that case you will get nodes in the reverse order.
You can implement extra options: TraverseDirectionForward and
TraverseDirectionReverse and use it for conditional `callback` method call
inside the `forEach` method.
Fill free to send a PR.

**Comment by recoilme** [comment]
Thank you! I will try

**Comment by recoilme** [comment]
PR: https://github.com/plar/go-adaptive-radix-tree/pull/3
