### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by DarkGhostHunter** [plar/go-adaptive-radix-tree#20]
ART trees are useful for using with HTTP Routers, but this implementation lacks wildcards.

```go
http.Router.Register("foo/{bar}/quz", "custom value")
```

That above should match a path like `foo/good-day/quz`. I could have made a fork which implements wildcards adding a node exclusively for the wildcards, and adding an member to identify which branch is a wildcard to fallback if none matches, but there is too much verbose code I don't know what the fuck what does what and why.

**Comment by plar** [comment]
The HTTP router support is not part of the project scope, so feel free to make a fork and hack around. :)

You can also check different implementations of [Go HTTP routers](https://github.com/avelino/awesome-go#routers).
