### ISSUE TITLE
Any plan to add generics support for values?

### ISSUE THREAD

**Issue by pablitovicente** [plar/go-adaptive-radix-tree#29]
I am using this library for building a cache and it is amazing. 

Are there any plans to support generics for the values? Although typecasting is fine I think supporting generics could be an interesting option.

**Comment by Misaka19327** [comment]
https://github.com/Misaka19327/MisakaDB/tree/main/customDataStructure/adaptiveRadixTree

**Comment by Misaka19327** [comment]
https://github.com/Misaka19327/MisakaDB/tree/main/customDataStructure/adaptiveRadixTree

**Comment by Misaka19327** [comment]
https://github.com/Misaka19327/MisakaDB/tree/main/customDataStructure/adaptiveRadixTree

I copy from this author's code and rewrite it to add generics support. Hope this helps you.

**Comment by plar** [comment]
@pablitovicente, the generic is quite easy to implement, you can do it like [this example](https://github.com/plar/go-adaptive-radix-tree/tree/master/examples/gtree) for your needs. In any case, people (including me) use a wrapper around the ART. :)

Something like this can live in your project package somewhere with your own preferences.

**Comment by pablitovicente** [comment]
Thanks!
