### ISSUE TITLE
Ordered Iteration mechanics

### ISSUE THREAD

**Issue by MadsRC** [plar/go-adaptive-radix-tree#38]
This is a great library!

While testing out the library for potential use-cases, I was surprised by the ordering mechanics. Given that the documentation only mentions "ordered iteration" briefly, I thought it might be an idea to ask for the ordering semantics to be documented.

I wrote the following test to verify that the library functioned as I expected:

```
func TestART_iteration_order(t *testing.T) {
	l := art.New()

	l.Insert([]byte("1234-1"), "value1")
	l.Insert([]byte("1234-2"), "value2")
	l.Insert([]byte("1234-10"), "value3")
	l.Insert([]byte("1234-100"), "value4")

	out := make([]string, 0)
	iter := l.Iterator()
	for iter.HasNext() {
		k, _ := iter.Next()
		out = append(out, string(k.Key()))
	}

	expectedOrder := []string{"1234-1", "1234-2", "1234-10", "1234-100"}

	require.Len(t, out, 4)
	require.Equal(t, expectedOrder, out)

}
```

That test fails, as the library iterates the keys in the order of `1234-1`, `1234-10`, `1234-100`, `1234-2`.

Is that the intended behavior, or is the ordering a bug?

**Comment by plar** [comment]
The ordering behavior you're observing is expected and not a bug but rather an expected consequence of how an Adaptive Radix Tree or similar data structure typically works.

The library performs _lexicographical_ ordering of keys, which compares keys byte by byte. 

For keys: 

```
"1234-1", "1234-2", "1234-10", "1234-100"
```

The lexicographical order is:

```
"1234-1" < "1234-10" < "1234-100" < "1234-2"
```

### Workarounds:

If numerical ordering is required, consider the following:

- Pad numbers with leading zeros for fixed-width sorting: `1234-0001, 1234-0002, 1234-0010, 1234-0100`
- post-process the keys after iteration to sort them numerically if padding is not feasible.

**Comment by MadsRC** [comment]
Thank you for clearing this up @plar - In hindsight, lexicographical ordering makes sense and I had already made a workaround by zero-padding as you also end up proposing.
