### ISSUE TITLE
Persistence?

### ISSUE THREAD

**Issue by mattkanwisher** [plar/go-adaptive-radix-tree#5]
Curious if you ever tried to make this data-structure persisted into a key value store?

**Comment by plar** [comment]
Do you mean a simple save/load feature or full fledged key/value storage like Redis, RocksDB, DynamoDB, etc? 

The save/load feature is pretty easy to implement, ART internal structures are simple. 
Storages like Redis/RocksDB are pretty hard and require good amount of time/tests/resources to implement.
